# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddSiteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSiteWindow(object):
    def setupUi(self, AddSiteWindow):
        AddSiteWindow.setObjectName("AddSiteWindow")
        AddSiteWindow.resize(264, 67)
        self.gridLayout = QtWidgets.QGridLayout(AddSiteWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AddSiteWindow)
        self.label.setMinimumSize(QtCore.QSize(75, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditSiteName = QtWidgets.QLineEdit(AddSiteWindow)
        self.lineEditSiteName.setObjectName("lineEditSiteName")
        self.gridLayout.addWidget(self.lineEditSiteName, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddSiteWindow)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(AddSiteWindow)
        self.buttonBox.accepted.connect(AddSiteWindow.accept)
        self.buttonBox.rejected.connect(AddSiteWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(AddSiteWindow)

    def retranslateUi(self, AddSiteWindow):
        _translate = QtCore.QCoreApplication.translate
        AddSiteWindow.setWindowTitle(_translate("AddSiteWindow", "AddSite"))
        self.label.setText(_translate("AddSiteWindow", "사이트 이름"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSiteWindow = QtWidgets.QDialog()
    ui = Ui_AddSiteWindow()
    ui.setupUi(AddSiteWindow)
    AddSiteWindow.show()
    sys.exit(app.exec_())
