# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FindIDWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IDFindWindow(object):
    def setupUi(self, IDFindWindow):
        IDFindWindow.setObjectName("IDFindWindow")
        IDFindWindow.resize(220, 333)
        self.gridLayout = QtWidgets.QGridLayout(IDFindWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(IDFindWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.listWidgetIDs = QtWidgets.QListWidget(IDFindWindow)
        self.listWidgetIDs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetIDs.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listWidgetIDs.setObjectName("listWidgetIDs")
        self.gridLayout.addWidget(self.listWidgetIDs, 0, 0, 1, 1)

        self.retranslateUi(IDFindWindow)
        self.buttonBox.accepted.connect(IDFindWindow.accept)
        self.buttonBox.rejected.connect(IDFindWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(IDFindWindow)

    def retranslateUi(self, IDFindWindow):
        _translate = QtCore.QCoreApplication.translate
        IDFindWindow.setWindowTitle(_translate("IDFindWindow", "Stored IDs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IDFindWindow = QtWidgets.QDialog()
    ui = Ui_IDFindWindow()
    ui.setupUi(IDFindWindow)
    IDFindWindow.show()
    sys.exit(app.exec_())
