# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InputKey.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogInputKeyWindow(object):
    def setupUi(self, DialogInputKeyWindow):
        DialogInputKeyWindow.setObjectName("DialogInputKeyWindow")
        DialogInputKeyWindow.resize(283, 93)
        self.gridLayout = QtWidgets.QGridLayout(DialogInputKeyWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditKey = QtWidgets.QLineEdit(DialogInputKeyWindow)
        self.lineEditKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditKey.setObjectName("lineEditKey")
        self.gridLayout.addWidget(self.lineEditKey, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogInputKeyWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(DialogInputKeyWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(DialogInputKeyWindow)
        self.buttonBox.accepted.connect(DialogInputKeyWindow.accept)
        self.buttonBox.rejected.connect(DialogInputKeyWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogInputKeyWindow)

    def retranslateUi(self, DialogInputKeyWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogInputKeyWindow.setWindowTitle(_translate("DialogInputKeyWindow", "Input Key"))
        self.label.setText(_translate("DialogInputKeyWindow", "복호화 키를 입력하세요."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogInputKeyWindow = QtWidgets.QDialog()
    ui = Ui_DialogInputKeyWindow()
    ui.setupUi(DialogInputKeyWindow)
    DialogInputKeyWindow.show()
    sys.exit(app.exec_())
