# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PWMMainWindow(object):
    def setupUi(self, PWMMainWindow):
        PWMMainWindow.setObjectName("PWMMainWindow")
        PWMMainWindow.resize(728, 140)
        self.centralwidget = QtWidgets.QWidget(PWMMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxSiteList = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSiteList.setObjectName("comboBoxSiteList")
        self.gridLayout.addWidget(self.comboBoxSiteList, 0, 0, 1, 2)
        self.pushButtonFindID = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFindID.setObjectName("pushButtonFindID")
        self.gridLayout.addWidget(self.pushButtonFindID, 0, 4, 1, 1)
        self.lineEditPW = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPW.setText("")
        self.lineEditPW.setDragEnabled(True)
        self.lineEditPW.setReadOnly(True)
        self.lineEditPW.setClearButtonEnabled(False)
        self.lineEditPW.setObjectName("lineEditPW")
        self.gridLayout.addWidget(self.lineEditPW, 2, 3, 1, 2)
        self.pushButtonDeleteSite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteSite.setObjectName("pushButtonDeleteSite")
        self.gridLayout.addWidget(self.pushButtonDeleteSite, 2, 1, 1, 1)
        self.pushButtonAddSite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddSite.setObjectName("pushButtonAddSite")
        self.gridLayout.addWidget(self.pushButtonAddSite, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.pushButtonMakePW = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMakePW.setObjectName("pushButtonMakePW")
        self.gridLayout.addWidget(self.pushButtonMakePW, 3, 0, 1, 5)
        self.lineEditID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditID.setDragEnabled(True)
        self.lineEditID.setReadOnly(False)
        self.lineEditID.setObjectName("lineEditID")
        self.gridLayout.addWidget(self.lineEditID, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        PWMMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PWMMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        PWMMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PWMMainWindow)
        self.statusbar.setObjectName("statusbar")
        PWMMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PWMMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PWMMainWindow)

    def retranslateUi(self, PWMMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PWMMainWindow.setWindowTitle(_translate("PWMMainWindow", "PWM"))
        self.pushButtonFindID.setText(_translate("PWMMainWindow", "아이디 기록"))
        self.pushButtonDeleteSite.setText(_translate("PWMMainWindow", "사이트 삭제"))
        self.pushButtonAddSite.setText(_translate("PWMMainWindow", "사이트 추가"))
        self.label.setText(_translate("PWMMainWindow", "비밀번호"))
        self.pushButtonMakePW.setText(_translate("PWMMainWindow", "생성"))
        self.label_2.setText(_translate("PWMMainWindow", "아이디"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PWMMainWindow = QtWidgets.QMainWindow()
    ui = Ui_PWMMainWindow()
    ui.setupUi(PWMMainWindow)
    PWMMainWindow.show()
    sys.exit(app.exec_())
